services running. except producer requires login?

diff --git a/scripts/start-all b/scripts/start-all
--- a/scripts/start-all
+++ b/scripts/start-all
@@ -16,62 +16,55 @@ else
   log_message "Zookeeper is running"
 fi
 
-
-log_message "Starting Kafka attached... "
+# delete the metadata file if it exists
+metadata_file="data/kafka/meta.properties"
+if [ -f ${metadata_file} ]; then
+    log_message "DANGER: removing ${metadata_file} for second attempt"
+    rm ${metadata_file}
+else
+    log_message "${metadata_file} not found"
+fi
 
 total_seconds_waited=0
 RETRY_SECONDS=10 # number of seconds to wait before retrying
 MAX_ATTEMPTS=5 # Number of attempts to check if Kafka is ready
 ATTEMPT=0
 
+# Start of the kafka-attampt-loop
 while [ $ATTEMPT -lt $MAX_ATTEMPTS ]; do
-  log_message "Attempt $ATTEMPT: Starting Kafka..."
-  
-  if [ $ATTEMPT -eq 1 ]; then
-    metadata_file="data/kafka/meta.properties"
-    if [ -f ${metadata_file} ]; then
-        log_message "DANGER: removing ${metadata_file} for second attempt"
-        rm ${metadata_file}
+    log_message "Starting Kafka - attempt $ATTEMPT: ..."
+    
+    # Here's start kafka attempt # $ATTEMPT
+    docker compose -f docker/docker-compose.yml up -d kafka; 
+
+    # Wait for Kafka to start and become fully operational
+    if ! ./scripts/wait-for-service kafka 9092 3 15 true; then
+        log_message "Kafka failed to start and become oerational within inside timeout"
+        log_message "continuing to the next-increment of the kafka-attempt-loop"
     else
-        log_message "${metadata_file} not found"
+        log_message "Kafka is running and operational on attempt ${ATTEMPT}"
+        log_message "Now Breaking out of the kafka-attempt-loop"
+        break
     fi
-  fi
-
-  # detached="-d"
-  detached=""
   
-  # Here's start kafka attempt # $ATTEMPT
-  log_message "Starting kafka detached attempt: ${ATTEMPT}... "
-  if ! docker compose -f docker/docker-compose.yml up #{detached} kafka; then
-      log_message "Kafka Failed to start or become available on attempt ${ATTEMPT}"
-  else
-      log_message "Kafka container started on attempt ${ATTEMPT}, now checking if Kafka is operational..."
+    # the next-increment of the kafka-attempt-loop 
+    ATTEMPT=$((ATTEMPT + 1))
+    if [ $ATTEMPT -lt $MAX_ATTEMPTS ]; then
+        log_message "Kafka failed to start on attempt:${ATTEMPT}"
+        log_message "retrying in ${RETRY_SECONDS} seconds..."
+        sleep ${RETRY_SECONDS}
+        total_seconds_waited=$((total_seconds_waited + RETRY_SECONDS))
+    else
+        log_message "Kafka failed to start after ${MAX_ATTEMPTS} attempts"
+        log_message "Exiting kafka-attempts-loop with status 1"
+        exit 1
+    fi
 
-      # Check if Kafka is operational
-      if scripts/kafka_is_operational; then
-          log_message "Kafka is operational. Breaking out of attemopts loop"
-          break
-      else
-          log_message "Kafka is not operational yet. Continuing to next attempt."
-      fi  
-  fi
-  
-  ATTEMPT=$((ATTEMPT + 1))
-  if [ $ATTEMPT -lt $MAX_ATTEMPTS ]; then
-      log_message "Kafka failed to start on attempt:${ATTEMPT}, retrying in ${RETRY_SECONDS} seconds..."
-      sleep ${RETRY_SECONDS}
-      total_seconds_waited=$((total_seconds_waited + RETRY_SECONDS))
-  else
-      log_message "Kafka failed to start after ${MAX_ATTEMPTS} attempts"
-      log_message "Exiting with status 1"
-      exit 1
-  fi
-
-# return to the top of the ATTEMPTS loop
+# return to the top of the kafka-attempt-loop
 done
 
 
-# prepaire to create the topic
+# Now prepaire to create the topic
 topic="user-login"
 
 existing_topics=$(docker compose -f docker/docker-compose.yml exec kafka /usr/bin/kafka-topics --bootstrap-server localhost:9092 --list)
@@ -87,6 +80,7 @@ else
     else
         echo "Failed to create topic ${topic}"
         exit 1
+    fi
 fi
 
 echo "Starting producer detached... "
