refinements to stop-all and start-all

diff --git a/scripts/start-all b/scripts/start-all
--- a/scripts/start-all
+++ b/scripts/start-all
@@ -43,56 +43,53 @@ while [ $ATTEMPT -lt $MAX_ATTEMPTS ]; do
   # Here's start kafka attempt # $ATTEMPT
   log_message "Starting kafka detached attempt: ${ATTEMPT}... "
   if ! docker compose -f docker/docker-compose.yml up #{detached} kafka; then
-    log_message "Kafka Failed to start or become availableKafka on attempt ${ATTEMPT}"
+      log_message "Kafka Failed to start or become available on attempt ${ATTEMPT}"
   else
-    log_message "Kafka container started on attempt ${ATTEMPT}, now checking if Kafka is operational..."
+      log_message "Kafka container started on attempt ${ATTEMPT}, now checking if Kafka is operational..."
 
-    # Check if Kafka is operational
-    if scripts/kafka_is_operational; then
-      log_message "Kafka is operational."
-      break
-    else
-      log_message "Kafka is not operational yet. "
-    fi  
+      # Check if Kafka is operational
+      if scripts/kafka_is_operational; then
+          log_message "Kafka is operational. Breaking out of attemopts loop"
+          break
+      else
+          log_message "Kafka is not operational yet. Continuing to next attempt."
+      fi  
   fi
   
   ATTEMPT=$((ATTEMPT + 1))
   if [ $ATTEMPT -lt $MAX_ATTEMPTS ]; then
-    log_message "Kafka failed to start on attempt:${ATTEMPT}, retrying in ${RETRY_SECONDS} seconds..."
-    sleep ${RETRY_SECONDS}
-    total_seconds_waited=$((total_seconds_waited + RETRY_SECONDS))
+      log_message "Kafka failed to start on attempt:${ATTEMPT}, retrying in ${RETRY_SECONDS} seconds..."
+      sleep ${RETRY_SECONDS}
+      total_seconds_waited=$((total_seconds_waited + RETRY_SECONDS))
+  else
+      log_message "Kafka failed to start after ${MAX_ATTEMPTS} attempts"
+      log_message "Exiting with status 1"
+      exit 1
   fi
 
-  # return to the top of the loop
+# return to the top of the ATTEMPTS loop
 done
 
-# Wait for Kafka to be fully up and running
-if ./scripts/wait-for-service kafka 9092; then
-  log_message "Kafka is running and operational"
-else
-  log_message "Kafka failed to start or become available within ${MAX_ATTEMPTS} attempts over ${total_seconds_waited} seconds"
-  log_message "Exiting with status 1"
-  exit 1
-fi
 
+# prepaire to create the topic
 topic="user-login"
 
 existing_topics=$(docker compose -f docker/docker-compose.yml exec kafka /usr/bin/kafka-topics --bootstrap-server localhost:9092 --list)
 if echo $existing_topics | grep -q ${topic}; then
-  echo "Topic ${topic} already exists"
+    echo "Topic ${topic} already exists"
 else
-  echo "Creating topic ${topic}"
-  docker compose -f docker/docker-compose.yml exec kafka /usr/bin/kafka-topics --bootstrap-server localhost:9092 --create --topic ${topic} --replication-factor 1 --partitions 1
+    echo "Creating topic ${topic}"
+    docker compose -f docker/docker-compose.yml exec kafka /usr/bin/kafka-topics --bootstrap-server localhost:9092 --create --topic ${topic} --replication-factor 1 --partitions 1
 
-  existing_topics=$(docker compose -f docker/docker-compose.yml exec kafka /usr/bin/kafka-topics --bootstrap-server localhost:9092 --list)
-  if echo $existing_topics | grep -q ${topic}; then
-    echo "Topic ${topic} created successfully"
-  else
-    echo "Failed to create topic ${topic}"
-    exit 1
+    existing_topics=$(docker compose -f docker/docker-compose.yml exec kafka /usr/bin/kafka-topics --bootstrap-server localhost:9092 --list)
+    if echo $existing_topics | grep -q -i ${topic}; then
+        echo "Topic ${topic} created successfully"
+    else
+        echo "Failed to create topic ${topic}"
+        exit 1
 fi
 
-# echo "Starting producer detached... "
+echo "Starting producer detached... "
 docker compose -f docker/docker-compose.yml up -d producer
 
 
